### ISSUE TITLE
App Store Deployment

### ISSUE THREAD

**Issue by jmolayem** [minhtule/Tapster-iOS-Demo#1]
Hi,

This a really interesting demo. I'm curious if you have any issues deploying to the app store. How does the recommendation algos work on the database? It seems like predictionIO locally installed my database.

**Comment by minhtule** [comment]
Hi!

I didn't submit this demo to AppStore but I think there shouldn't be any issue (except that it hasn't been updated to the latest Swift version). 

Regarding the recommendation algo, you might want to check the template's instruction provided by PredictionIO [here](http://templates.prediction.io/PredictionIO/template-scala-parallel-similarproduct). The algo is collaborative filtering.

Just to be clear, the iOS demo has no local database. All user events are sent to PredictionIO's event server for storage and processing. And PredictionIO's event server/database can be set up on the cloud.

**Comment by jmolayem** [comment]
Oh, I see. I didn't see a login/access keys anywhere on PredictionIO. Do I have to use a separate service (heroku, amazon, etc) to set this up?

**Comment by minhtule** [comment]
Yeah, you can launch PredictionIO on AWS (instructions [here](https://docs.prediction.io/install/launch-aws/)). Please see the [guide](https://docs.prediction.io/templates/recommendation/quickstart) on how to create PredictionIO's AppID and AccessKey.

**Comment by jmolayem** [comment]
Great. In this instance, there would be no need to download Hbase and spark locally right

**Comment by minhtule** [comment]
When you download and install PredictionIO, Spark and HBase will also be installed.

**Comment by jmolayem** [comment]
I see. I was reading in your documentation that

let eventClient = EventClient(accessKey: " < Your App ID here > ")

should it be 

let eventClient = EventClient(accessKey: " < Access Key > ")? The "App ID" doesn't sound like the proper authenticator.

**Comment by minhtule** [comment]
You're right! It should be the access key as the outer parameter name of the initializer indicates. :grin:
